# Generated by Django 4.2.6 on 2024-01-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_restaurant_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="numberOfDiners",
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reservation",
            name="time",
            field=models.DateTimeField(),
        ),
    ]
