# Generated by Django 4.2.6 on 2024-01-25 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_reservation_numberofdiners_alter_reservation_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restaurant",
            old_name="tables",
            new_name="reserverdTables",
        ),
    ]
