# Generated by Django 5.0 on 2024-01-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_remove_reservation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='shift',
            field=models.CharField(choices=[('10AM - 12PM', 'First'), ('12PM - 2PM', 'Second'), ('2PM - 4PM', 'Third'), ('4PM - 6PM', 'Fourth'), ('6PM - 8PM', 'Fifth'), ('8PM - 10PM', 'Sixth'), ('10PM - 12AM', 'Seventh')], max_length=11),
        ),
    ]
