# Generated by Django 5.0 on 2024-01-31 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_alter_reservation_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='shift',
        ),
    ]
