# Generated by Django 5.0 on 2024-01-31 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_reservation_shift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='shift',
            new_name='shiftRange',
        ),
    ]
