# Generated by Django 5.0 on 2024-01-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_remove_shift_reserverdtables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='personCapacity',
            field=models.IntegerField(default=-1, editable=False),
        ),
        migrations.AlterField(
            model_name='shift',
            name='tablesCapacity',
            field=models.IntegerField(default=-1, editable=False),
        ),
    ]
