# Generated by Django 5.0 on 2024-02-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_remove_restaurant_isfull_alter_shift_personcapacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='imgURL',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
