# Generated by Django 5.0 on 2024-02-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_restaurant_address_restaurant_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='imgURL',
            field=models.CharField(max_length=1000),
        ),
    ]
