# Generated by Django 4.2.6 on 2024-02-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0020_rename_imgurl_restaurant_img_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="shiftRange",
            field=models.CharField(max_length=14),
        ),
    ]
