# Generated by Django 5.0 on 2024-02-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0021_alter_shift_shiftrange'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
