# Generated by Django 5.0 on 2024-02-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0022_reservation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='when_reserved',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
