# Generated by Django 5.0 on 2024-02-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0023_reservation_when_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
