# Generated by Django 5.0 on 2024-02-11 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0024_reservation_active_alter_reservation_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='when_reserved',
            new_name='timestamp',
        ),
    ]
